name: Deploy Webpage
on: workflow_dispatch

jobs:
  build:
    runs-on: ubunutu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: install emsdk
        run:  python fips emsdk install latest
      - name: build
        run: |
          python set local on
          python fips webpage build
      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with: webpage
        path: fips-files/deploy/webpage
        retention-days: 1

